/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "srv.h"


CORBA_double srv_add(srv _obj, const CORBA_double i, const CORBA_double j, CORBA_Environment *ev){
CORBA_double _ORBIT_retval;
gpointer _args[2];
_args[0] = (gpointer)&i;
_args[1] = (gpointer)&j;
ORBit_c_stub_invoke (_obj, &srv__iinterface.methods, 0, &_ORBIT_retval, _args, NULL, ev, srv__classid, G_STRUCT_OFFSET (POA_srv__epv, add),
(ORBitSmallSkeleton) _ORBIT_skel_small_srv_add);

return _ORBIT_retval;
}
