/* This is a template file generated by command */
/* orbit-idl-2 --skeleton-impl srv.idl */
/* User must edit this file, inserting servant  */
/* specific code between markers. */

#include "srv.h"

/*** App-specific servant structures ***/

#if !defined(_typedef_impl_POA_srv_)
#define _typedef_impl_POA_srv_ 1
typedef struct {
POA_srv servant;
PortableServer_POA poa;
   /* ------ add private attributes here ------ */
   /* ------ ---------- end ------------ ------ */
} impl_POA_srv;
#endif


/*** Implementation stub prototypes ***/

#if !defined(_decl_impl_srv__destroy_)
#define _decl_impl_srv__destroy_ 1
static void impl_srv__destroy(impl_POA_srv *servant,
CORBA_Environment *ev);
#endif

#if !defined(_decl_impl_srv_add_)
#define _decl_impl_srv_add_ 1
static CORBA_double
impl_srv_add(impl_POA_srv *servant,
const CORBA_double i,
const CORBA_double j,
CORBA_Environment *ev);
#endif


/*** epv structures ***/

#if !defined(_impl_srv_base_epv_)
#define _impl_srv_base_epv_ 1
static PortableServer_ServantBase__epv impl_srv_base_epv = {
NULL,             /* _private data */
(gpointer) & impl_srv__destroy, /* finalize routine */
NULL,             /* default_POA routine */
};
#endif

#if !defined(_impl_srv_epv_)
#define _impl_srv_epv_ 1
static POA_srv__epv impl_srv_epv = {
NULL, /* _private */
(gpointer)&impl_srv_add,
};
#endif


/*** vepv structures ***/

#if !defined(_impl_srv_vepv_)
#define _impl_srv_vepv_ 1
static POA_srv__vepv impl_srv_vepv = {
&impl_srv_base_epv,
&impl_srv_epv,
};
#endif


/*** Stub implementations ***/

#if !defined(_impl_srv__create_)
#define _impl_srv__create_ 1
static srv impl_srv__create(PortableServer_POA poa, CORBA_Environment *ev)
{
srv retval;
impl_POA_srv *newservant;
PortableServer_ObjectId *objid;

newservant = g_new0(impl_POA_srv, 1);
newservant->servant.vepv = &impl_srv_vepv;
newservant->poa = (PortableServer_POA) CORBA_Object_duplicate((CORBA_Object)poa, ev);
POA_srv__init((PortableServer_Servant)newservant, ev);
   /* Before servant is going to be activated all
    * private attributes must be initialized.  */

   /* ------ init private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

objid = PortableServer_POA_activate_object(poa, newservant, ev);
CORBA_free(objid);
retval = PortableServer_POA_servant_to_reference(poa, newservant, ev);

return retval;
}
#endif

#if !defined(_impl_srv__destroy_)
#define _impl_srv__destroy_ 1
static void
impl_srv__destroy(impl_POA_srv *servant, CORBA_Environment *ev)
{
    CORBA_Object_release ((CORBA_Object) servant->poa, ev);

    /* No further remote method calls are delegated to 
    * servant and you may free your private attributes. */
   /* ------ free private attributes here ------ */
   /* ------ ---------- end ------------- ------ */

POA_srv__fini((PortableServer_Servant)servant, ev);

g_free (servant);
}
#endif

#if !defined(_impl_srv_add_)
#define _impl_srv_add_ 1
static CORBA_double
impl_srv_add(impl_POA_srv *servant,
const CORBA_double i,
const CORBA_double j,
CORBA_Environment *ev)
{
CORBA_double retval;
 /* ------   insert method code here   ------ */
 /* ------ ---------- end ------------ ------ */

return retval;
}
#endif

