/*
 * This file was generated by orbit-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define ORBIT2_STUBS_API
#include "srv.h"

static ORBitSmallSkeleton get_skel_small_srv(POA_srv *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case 'a':
if(strcmp((opname + 1), "dd")) break;
*impl = (gpointer)servant->vepv->srv_epv->add;
{ORBit_IInterface *volatile _t_=&srv__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (ORBitSmallSkeleton)_ORBIT_skel_small_srv_add;
break;
default: break; 
}
return NULL;
}

void POA_srv__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (ORBit_small_impl_finder)&get_skel_small_srv, "IDL:srv:1.0", &srv__classid, NULL, &srv__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
   ORBit_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_srv__fini,
   ORBIT_VEPV_OFFSET (POA_srv__vepv, srv_epv),
   (CORBA_unsigned_long) 0);}

void POA_srv__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  PortableServer_ServantBase__fini(servant, env);
}

